### PR TITLE
initial Fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
Initial fastlane structure as discussed in #14. A few notes:

* be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this
* you might wish to replace the screenshots by "better quality/resolution". Looks like I'm preaching the choir with this, but my usual hint: keep mobile users with small screens and low bandwidth in mind, i.e. keep the (file) sizes reasonable and rather avoid framing :wink:
* some formatting hints for the `full_description.txt` can be found [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). I recommend what I called there "Markdown lite", as it proved to work well with all involved parties so far (all other variants have "strange results" for at least one of them).

Should there be questions, feel free to ask!

### CODE REVIEW

**Comment by IzzySoft** [comment]
Speed cam alert :rofl: That was fast, thanks! Cleaning up then on my end.

**Comment by JakeGonder** [comment]
Its called fast-lane for a reason! What specific resolution would you recommend for the screenshots?

**Comment by IzzySoft** [comment]
> Its called fast-lane for a reason!

:rofl: 

> What specific resolution would you recommend for the screenshots?

I use 350px width (portrait) in my repo, trying to keep each screenshot below 50kb (here: around 25kb). My updater automatically takes care for that, but AFAIK F-Droid just takes them as-is. If you feel it should be 700px, that should be OK. But if each screenshot is > 100kb (I've seen them exceeding 1 Mb at times), that might hurt those on low bandwidth. So it's mostly about finding a good compromise.

My argument usually is: screenshots here should give an idea about how the app looks like. It's not their intention to serve as high-res graphics gallery for art fans :smile:

**Comment by JakeGonder** [comment]
Hey @IzzySoft quick question, I recently (2 weeks ago) updated the [phone screenshots](https://github.com/RayLeaf-Studios/PocketPlan/tree/master/fastlane/metadata/android/en-US/images/phoneScreenshots) in the fastlane directory, but F-Droid [now shows a mix](https://f-droid.org/packages/com.pocket_plan.j7_003/) of the new and the old screenshots, do you have any idea why? Does it just take time on the side of F-Droid to properly update this, or does it by design show screenshots from old releases as well?

**Comment by IzzySoft** [comment]
Let me take an educated guess: you've removed oldies and added new ones using different names? If so: congrats for confirming that old bug is still alive :cry: [Repository keeps deleted screenshots](https://gitlab.com/fdroid/fdroidserver/-/issues/490)

**Comment by IzzySoft** [comment]
Currently you'd not get rid of what was once put up (that bug haunts us for at least 5 years now). So to get rid of the two old ones you'd need to add a screenshot for each to overwrite it, using the very same names (i.e. 01.jpg to 04.jpg). As the bug sits there for 5 years now not being solved, while brought up at least twice a year, I wouldn't place my bets on it being fixed within weeks.

**Comment by JakeGonder** [comment]
Thanks, I think that's what I'll try. I will also just use the opportunity to get the file size to ~50kb as you previously advised, since I noticed they are a bit high in resolution😁

**Comment by IzzySoft** [comment]
> I will also just use the opportunity to get the file size to ~50kb

Thanks! In my repo, the updater takes care for that, but F-Droid.org just takes it mostly as-is IIRC (at least, to my knowledge, there's no resizing – while in my repo the updater always resizes screenshots to max 350 px on the small side).

**Pull request merged**
